services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    autoDeploy: false
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        fromSecret: email_user
      - key: EMAIL_APP_PASS
        fromSecret: email_app_pass
      - key: RECIPIENT_EMAIL
        fromSecret: recipient_email
