services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    autoDeploy: false
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        value: diviyaprakash32@gmail.com
      - key: EMAIL_APP_PASS
        value: jlfnjwznuxqqrsqy
      - key: RECIPIENT_EMAIL
        value: diviyaprakash32@gmail.com
