services:
  - type: web
    name: divyaprakash-portfolio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
